# Generated by Django 2.1.3 on 2018-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send_mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75, verbose_name='Subject')),
                ('recipient_list', models.CharField(max_length=200, verbose_name='Recipient List')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(default='NEW', max_length=25)),
            ],
        ),
    ]
