# Generated by Django 2.1.3 on 2018-11-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_auto_20181129_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_mail',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='send_mail',
            name='recipient_list',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recipient List'),
        ),
    ]
