# Generated by Django 2.1.3 on 2018-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mail_address',
            field=models.EmailField(max_length=200, unique=True, verbose_name='E-mail Address'),
        ),
    ]
